// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import ()

type User struct {
	ID             int32
	Username       string
	Email          string
	PasswordDigest string
	IsAdmin        bool
}
