# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "make build-local"
# Binary file yields from `cmd`.
bin = "./bin/server/monolith"
# Customize binary.
full_bin = "./bin/server/monolith"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "js", "sql", "proto", "env"]
delay = 200
kill_delay = 500
