
CREATE TABLE IF NOT EXISTS `webcomic` (
    `webcomic_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` int(10) UNSIGNED NOT NULL,
    `active` tinyint(1) NOT NULL DEFAULT '1',
    `nsfw` tinyint(1) NOT NULL DEFAULT '0',
    `last_read` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ordinal` int(11) NOT NULL DEFAULT '0',
    `title` varchar(128) NOT NULL,
    `base_url` varchar(512) NOT NULL,
    `first_comic_url` varchar(512) DEFAULT NULL,
    `latest_comic_url` varchar(128) DEFAULT NULL,
    `rss_url` varchar(128) DEFAULT NULL,
    `updates_monday` tinyint(1) NOT NULL,
    `updates_tuesday` tinyint(1) NOT NULL DEFAULT '0',
    `updates_wednesday` tinyint(1) NOT NULL DEFAULT '0',
    `updates_thursday` tinyint(1) NOT NULL DEFAULT '0',
    `updates_friday` tinyint(1) NOT NULL DEFAULT '0',
    `updates_saturday` tinyint(1) NOT NULL DEFAULT '0',
    `updates_sunday` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (`webcomic_id`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`),
    UNIQUE KEY `title` (`title`),
    UNIQUE KEY `base_url` (`base_url`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
