// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"database/sql"
)

type RssItem struct {
	ItemID     int32
	WebcomicID int32
	UserID     int32
	IsRead     bool
	Guid       string
	Title      string
	Link       string
}

type User struct {
	UserID   int32
	Username string
	Email    string
	Passwd   string
}

type Webcomic struct {
	WebcomicID       int32
	Ordinal          sql.NullInt32
	UserID           int32
	Title            string
	BaseUrl          sql.NullString
	FirstComicUrl    sql.NullString
	LatestComicUrl   sql.NullString
	RssUrl           sql.NullString
	UpdatesMonday    bool
	UpdatesTuesday   bool
	UpdatesWednesday bool
	UpdatesThursday  bool
	UpdatesFriday    bool
	UpdatesSaturday  bool
	UpdatesSunday    bool
	Active           bool
	Nsfw             bool
	LastRead         sql.NullTime
}
