// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: users.sql

package queries

import (
	"context"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (username, email, passwd) VALUES ($1, $2, $3)
`

type AddUserParams struct {
	Username string
	Email    string
	Passwd   string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Username, arg.Email, arg.Passwd)
	return err
}
