name: 'Build Website: login'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/web/login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  build-login:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
        name: install npm dependencies
        working-directory: web/login 
      - run: npm run build
        name: compile 
        working-directory: web/login
      - name: Tar output files
        run: tar -czvf klaital-web-login.tar.gz *
        working-directory: web/login/build
      - name: Upload website tarball
        uses: actions/upload-artifact@v3
        with:
          name: klaital-web-login
          path: web/login/build/klaital-web-login.tar.gz
